#!/usr/bin/env bash

if [ -z "$1" ]
  then
    echo "Usage $0 CONTAINER"
	exit 1
fi

CONTAINER=$1

function occ() {
    docker compose exec "$CONTAINER" sudo -E -u www-data "./occ" "$@"
}

# shellcheck disable=SC1091
source .env

echo "Setting up Collabora with collabora$DOMAIN_SUFFIX on $CONTAINER"
if docker compose up -d collabora 2>/dev/null; then
    :
else
    docker-compose up -d collabora
fi
occ app:enable richdocuments
occ config:app:set richdocuments wopi_url --value="http://collabora${DOMAIN_SUFFIX}"
occ config:app:set richdocuments public_wopi_url --value="http://collabora${DOMAIN_SUFFIX}"
occ config:system:set allow_local_remote_servers --value true --type bool
occ config:system:set gs.trustedHosts 0 --value "*${DOMAIN_SUFFIX}"
occ richdocuments:activate-config
